### ISSUE TITLE
WebAuthn registration failure

### ISSUE THREAD

**Issue by rhawdor** [lukin/keywind#57]
Hello !

I recently updated to Keycloak 22 (more precisely 22.0.1, was using version 21 before), and I think I spotted a bug ?
```
Caused by: freemarker.core.NonStringOrTemplateOutputException: For "${...}" content: Expected a string or something automatically convertible to string (number, date or boolean), or "template output" , but this has evaluated to a sequence (wrapper: f.t.SimpleSequence):
==> signatureAlgorithms  [in template "webauthn-register.ftl" at line 47, column 31]
----
FTL stack trace ("~" means nesting-related):
 - Failed at: ${signatureAlgorithms}  [in template "webauthn-register.ftl" at line 47, column 29]
----
```

Could this be related to [#20831](https://github.com/keycloak/keycloak/issues/20831) or am I missing something ?

**Comment by paulwer** [comment]
Hey @rhawdor,
does this error was also present on kc 21.0.1?

**Comment by rhawdor** [comment]
Hey @paulwer !
To be extremely sure I reproduced it in a clean environment with fresh install from KC and keywind.

- With 22.0.3 the error happen when you want to register a WebAuthn security key.
- With 22.0.1 the security key is correctly registered.

So, to answer, no the error was not present on KC 21.0.1.

**Comment by paulwer** [comment]
i guess this is due to the following change in keycloak:
https://github.com/keycloak/keycloak/commit/1af4a7a5325c248da2275759379ec00e495045df

@lukin should we support the old and the new way for backwards compatibility?

**Comment by Clemv95** [comment]
I have this error too and this is annoying :/

**Comment by paulwer** [comment]
a workaround for now would be to stay on 21 from my pov, if this is an option😕

**Comment by Clemv95** [comment]
it's not really an option :/
How much time do you think it's gonna take ?

**Comment by paulwer** [comment]
i dont know.
are you able to debug yourself and PR a fix?
maybe we can start from there or move support to only the actual version?

tipp: look at the official integration mentioned beforw, what they changed...maybe this helps

**Comment by Clemv95** [comment]
I can try myself, but i dont think it's gonna be easy and fast, i'm not really familiar with typescript and tailwind

**Comment by paulwer** [comment]
from my pov its an issue from mapping internal data by ftl and output it to the script.
ytring changed to array. so the mapping behavior should be edited and not even necessary the typescript script

**Comment by Clemv95** [comment]
Where is the mapping behavior ? 
Maybe i can try

**Comment by paulwer** [comment]
the line, which is failing according to the error message is: https://github.com/lukin/keywind/blob/master/theme/keywind/login/webauthn-register.ftl#L47C31-L47C50

the variable within keycloak before was: a string separeted by "," and afterwards its a List in java.

Maybe try something like this:
<#if signatureAlgorithms?is_enumerable>${signatureAlgorithms?join(", ")}<#else>${signatureAlgorithms}</#if>

(means: if its an array => join it to string, seperated with "," OR if its anything else (probably a string, from versions before) => just display it as string in the html)

**Comment by tomas-rojo** [comment]
@paulwer Thanks for the snippet. I personally used it in my project, but this error happens:
```
Uncaught TypeError: t.split is not a function
    at L (webAuthnRegister.js:1:708)
    at Proxy.registerSecurityKey (webAuthnRegister.js:1:1150)
    at fe (module.esm-9a996e1c.js:5:1218)
    at module.esm-9a996e1c.js:5:1043
    at Zn (module.esm-9a996e1c.js:1:6454)
    at module.esm-9a996e1c.js:5:34963
    at o (module.esm-9a996e1c.js:5:24801)
    at module.esm-9a996e1c.js:5:25790
    at HTMLButtonElement.<anonymous> (module.esm-9a996e1c.js:5:24823)
```

**Comment by scheibling** [comment]
> the line, which is failing according to the error message is: https://github.com/lukin/keywind/blob/master/theme/keywind/login/webauthn-register.ftl#L47C31-L47C50
> 
> the variable within keycloak before was: a string separeted by "," and afterwards its a List in java.
> 
> Maybe try something like this:
> 
> ```
> <#if signatureAlgorithms?is_enumerable>${signatureAlgorithms?join(",")}<#else>${signatureAlgorithms}</#if>
> ```
> 
> (means: if its an array => join it to string, seperated with "," OR if its anything else (probably a string, from versions before) => just display it as string in the html)
> 
> and here is the line of official keycloak: https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/webauthn-register.ftl#L42

@paulwer Cheers man, this solved it for me. I've opened up a pull request with that line replaced
